### ISSUE TITLE
hyprexpo: ometimes unable to exit

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprland-plugins#126]
Hyprexpo sometimes goes into a state where clicking on workspaces won't select them anymore (just pass the input down to below the screen). normal `hyprexpo:expo toggle/disable/off` means won't help. The only way to close hyprexpo becomes to disable it

https://github.com/hyprwm/hyprland-plugins/assets/84153269/7fb48902-851a-4f12-8672-a9870e26b050

**Comment by vaxerski** [comment]
shouldn't be possible... how to repro? Never seen this.

**Comment by alba4k** [comment]
I'm still trying to figure that out (which is why I only opened the issue now, but it has been happening since I first tried out he)

Will let you know

**Comment by muhchaudhary** [comment]
Just experienced this as well when launching with 4 finger swipe.

**Comment by postsolar** [comment]
I can get it consistently but my setup is a bit nuanced:

1. I use [fusuma](https://github.com/iberianpig/fusuma?tab=readme-ov-file) to set up some gestures. My fusuma config is as follows:
```yaml
swipe:
  3:
    left:
      command: zsh -ic "hyprctl dispatch workspace m+1"
    right:
      command: zsh -ic "hyprctl dispatch workspace m-1"
    up:
      command: zsh -ic "hyprctl dispatch hyprexpo:expo toggle"

threshold:
  swipe: 0.2

interval:
  swipe: 0.7
```

2. My hyprexpo config is this:

```hyprlang
plugin {
  hyprexpo {
    bg_col = rgb(111111)
    columns = 4
    gap_size = 5
    workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
    enable_gesture = false # laptop touchpad, 4 fingers
    gesture_distance = 300 # how far is the "max"
    gesture_positive = true # positive = swipe down. Negative = swipe up.
  }
}
```

3. 3-fingers swipe up to toggle hyprexpo
4. 3-fingers swipe left
5. Get it stuck like in the vid above.

Not sure at all but I feel like that final swipe left gesture triggers both a click and the gesture.
